import Car1 from '../assets/car1.png';
import Car2 from '../assets/car2.png';
import Car3 from '../assets/car3.png';
import Car4 from '../assets/car4.png';
import Car5 from '../assets/car5.png';  // Add new car images
import Car6 from '../assets/car6.png';
import Car7 from '../assets/car7.png';
import Car8 from '../assets/car8.png';

const carList = [
  {
    id: 1,
    make: 'Tesla',
    model: 'Model S',
    year: 2020,
    price: '$80/day',
    image: Car1,
    seats: 5,
    doors: 4,
    suitcase: 2,
    airConditioning: true,
    petrol: 'Electric',
    automatic: true,
  },
  {
    id: 2,
    make: 'BMW',
    model: 'X5',
    year: 2017,
    price: '$75/day',
    image: Car2,
    seats: 5,
    doors: 4,
    suitcase: 3,
    airConditioning: true,
    petrol: 'Petrol',
    automatic: true,
  },
  {
    id: 3,
    make: 'Audi',
    model: 'A6',
    year: 2019,
    price: '$60/day',
    image: Car3,
    seats: 5,
    doors: 4,
    suitcase: 3,
    airConditioning: true,
    petrol: 'Diesel',
    automatic: true,
  },
  {
    id: 4,
    make: 'Mercedes-Benz',
    model: 'E-Class',
    year: 2019,
    price: '$90/day',
    image: Car4,
    seats: 5,
    doors: 4,
    suitcase: 3,
    airConditioning: true,
    petrol: 'Petrol',
    automatic: true,
  },
  {
    id: 5,
    make: 'Ford',
    model: 'Mustang',
    year: 2021,
    price: '$100/day',
    image: Car5,
    seats: 4,
    doors: 2,
    suitcase: 2,
    airConditioning: true,
    petrol: 'Petrol',
    automatic: false,
  },
  {
    id: 6,
    make: 'Chevrolet',
    model: 'Camaro',
    year: 2022,
    price: '$110/day',
    image: Car6,
    seats: 4,
    doors: 2,
    suitcase: 2,
    airConditioning: true,
    petrol: 'Petrol',
    automatic: true,
  },
  {
    id: 7,
    make: 'Toyota',
    model: 'Corolla',
    year: 2017,
    price: '$40/day',
    image: Car7,
    seats: 5,
    doors: 4,
    suitcase: 2,
    airConditioning: true,
    petrol: 'Petrol',
    automatic: true,
  },
  {
    id: 8,
    make: 'Honda',
    model: 'Civic',
    year: 2019,
    price: '$45/day',
    image: Car8,
    seats: 5,
    doors: 4,
    suitcase: 2,
    airConditioning: true,
    petrol: 'Petrol',
    automatic: true,
  },
];

export default carList;
